export const FETCH_CONTACTS_FAILURE = "FETCH_CONTACTS_FAILURE";
export const FETCH_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";

export const INIT_CONTACT = "INIT_CONTACT";
export const SET_MODAL = 'SET_MODAL';

export const CONTACT_FAILURE = "CONTACT_FAILURE";
export const CONTACT_REQUEST = "CONTACT_REQUEST";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";


